### ISSUE TITLE
Ha én futtatom, eltűnik a CSS

### ISSUE THREAD

**Issue by boapps** [bru02/eFilc#1]
Ha én próbálom futtatni az index.php-t, akkor eltűnik minden material-designos szépség és csak plain fekete-fehér az egész.

ezt a parancsot használtam:
`php -S localhost:8080 index.php`

Ha a [weboldaladon](https://www.bru02.tk/e-filc/) nézem, akkor minden tökéletes (és nagyon szép munka, gratulálok! :+1: ).

php verzióm:

> PHP 7.3.1 (cli) (built: Jan  8 2019 16:39:04) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies

errors.log tartalma:

> [29-Jan-2019 19:51:19 UTC] PHP Warning:  session_name(): Cannot change session name when headers already sent in /home/boa/efilc/eFilc/lib.php on line 6
> [29-Jan-2019 19:51:19 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in /home/boa/efilc/eFilc/lib.php on line 7
> [29-Jan-2019 19:51:19 UTC] PHP Notice:  Undefined index: REQUEST_URI in /home/boa/efilc/eFilc/lib.php on line 17
> [29-Jan-2019 19:51:19 UTC] PHP Notice:  Undefined index: SERVER_NAME in /home/boa/efilc/eFilc/index.php on line 21
> [29-Jan-2019 19:51:19 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/boa/efilc/eFilc/lib.php:1) in /home/boa/efilc/eFilc/lib.php on line 195

Rendszer:
> OS: Arch Linux x86_64
> Kernel Release: 4.19.13-1-MANJARO

Kéne hozzá valami egyéb külső könyvtár, vagy hasonló?

**Comment by bru02** [comment]
Igen, kell hozzá Apache, hogy értelmezze `.htaccess` -t.
Legegyszerűbb ha [xampp](https://www.apachefriends.org/hu/download.html#download-linux) -al probálod meg.

**Comment by boapps** [comment]
Feltettem az xamppot az [Arch Wiki utasításai](https://wiki.archlinux.org/index.php/XAMPP) szerint, de nem változott semmi.
Az alábbi sorokat írtam a `/opt/lampp/etc/httpd.conf` fájlba:
```
<Directory "/home/boa/efilc/eFilc/">
    Options Indexes FollowSymLinks ExecCGI Includes
    AllowOverride All
    Require all granted
</Directory>
```

```
Alias /efilc /home/boa/efilc/eFilc/
```

`http://localhost/efilc/login`: erre az URL-re ugyanaz a fekete-fehér formázatlan csúnyaság jön be mint eddig.

Bocsi, ha egyértelmű a válasz, de nekem most a google se segített :(

**Comment by bru02** [comment]
Nincsen lekezelve, hogy ha `htdocs`-on kivül van az eFilc (meg ha aliast használsz).
Szóval commenteld ki (`#`-el) amit beleírtál a `httpd.conf`-ba és másold át a `/home/boa/efilc/eFilc` mappát a `/opt/lampp/htdocs` mappába és elvileg müködni fog.

**Comment by boapps** [comment]
És a htdocs jelenlegi tartalmát töröljem előtte?

**Comment by boapps** [comment]
Köszi! Megoldódott, zárom az issuet!
